baseURL = "https://rickyzhf.cc/"

# æ›´æ”¹ä½¿ç”¨ Hugo æ„å»ºç½‘ç«™æ—¶ä½¿ç”¨çš„é»˜è®¤ä¸»é¢˜
theme = "LoveIt"

# ç½‘ç«™æ ‡é¢˜
title = "rickyy"

# ç½‘ç«™è¯­è¨€, ä»…åœ¨è¿™é‡Œ CN å¤§å†™ ["en", "zh-CN"]
languageCode = "zh-CN"
# è¯­è¨€åç§° ["English", "ç®€ä½“ä¸­æ–‡", "FranÃ§ais", "Polski", ...]
languageName = "ç®€ä½“ä¸­æ–‡"
# æ˜¯å¦åŒ…æ‹¬ä¸­æ—¥éŸ©æ–‡å­—
hasCJKLanguage = true
# è¿™ä¸ªä¹Ÿè¦è®¾ç½®
defaultContentLanguage = "zh-cn"

# æœç´¢ç”¨
[outputs]
  home = ["HTML", "RSS", "JSON"]

# ä½œè€…é…ç½®
[author]
  name = "ricky"
  email = "568058082@qq.com"
  link = ""

# æ˜¯å¦ä½¿ç”¨ robots.txt
enableRobotsTXT = true
# æ˜¯å¦ä½¿ç”¨ git ä¿¡æ¯
enableGitInfo = true
# æ˜¯å¦ä½¿ç”¨ emoji ä»£ç 

# å¿½ç•¥ä¸€äº›æ„å»ºé”™è¯¯
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# èœå•é…ç½®
[menu]
  [[menu.main]]
    weight = 1
    identifier = "home"
    pre = "ğŸ "
    post = ""
    name = " ä¸»é¡µ"
    url = "/"
    title = ""
  [[menu.main]]
    weight = 20
    identifier = "posts"
    # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
    pre = "ğŸ•¥"
    # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
    post = ""
    name = "æ—¶é—´"
    url = "/posts/"
    # å½“ä½ å°†é¼ æ ‡æ‚¬åœåœ¨æ­¤èœå•é“¾æ¥ä¸Šæ—¶, å°†æ˜¾ç¤ºçš„æ ‡é¢˜
    title = ""
    [[menu.main]]
    weight = 10
    identifier = "categories"
    pre = "ğŸ—‚ï¸"
    post = ""
    name = "ç±»ç›®"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 30
    identifier = "tags"
    pre = "ğŸ·ï¸"
    post = ""
    name = "æ ‡ç­¾"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 40
    identifier = "about"
    pre = "ğŸªª"
    post = ""
    name = "å…³äº"
    url = "/about/"
    title = ""


# Hugo è§£ææ–‡æ¡£çš„é…ç½®
[markup]
  # è¯­æ³•é«˜äº®è®¾ç½® (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false æ˜¯å¿…è¦çš„è®¾ç½® (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
    # ä½¿ç”¨<MARK>æ ‡è®°é«˜äº®æ—¶éœ€è¦è®¾ç½®è¯¥é€‰é¡¹ä¸ºå¼€å¯
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

[params]
  # ç½‘ç«™é»˜è®¤ä¸»é¢˜æ ·å¼ ["auto", "light", "dark"]
  defaultTheme = "auto"
  # å…¬å…± git ä»“åº“è·¯å¾„ï¼Œä»…åœ¨ enableGitInfo è®¾ä¸º true æ—¶æœ‰æ•ˆ
  gitRepo = ""
  # LoveIt æ–°å¢ | 0.1.1 å“ªç§å“ˆå¸Œå‡½æ•°ç”¨æ¥ SRI, ä¸ºç©ºæ—¶è¡¨ç¤ºä¸ä½¿ç”¨ SRI
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # LoveIt æ–°å¢ | 0.2.0 æ—¥æœŸæ ¼å¼
  dateFormat = "2006-01-02"
  # ç½‘ç«™æ ‡é¢˜, ç”¨äº Open Graph å’Œ Twitter Cards
  title = "Ricky ZhouHuaiFeng"
  # ç½‘ç«™æè¿°, ç”¨äº RSS, SEO, Open Graph å’Œ Twitter Cards
  description = "zhou huaifeng"
  # ç½‘ç«™å›¾ç‰‡, ç”¨äº Open Graph å’Œ Twitter Cards
  images = ["/img/self.gif"]
  # é¡µé¢å¤´éƒ¨å¯¼èˆªæ é…ç½®
  [params.header]
    # æ¡Œé¢ç«¯å¯¼èˆªæ æ¨¡å¼ ["fixed", "normal", "auto"]
    desktopMode = "auto"
    # ç§»åŠ¨ç«¯å¯¼èˆªæ æ¨¡å¼ ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt æ–°å¢ | 0.2.0 é¡µé¢å¤´éƒ¨å¯¼èˆªæ æ ‡é¢˜é…ç½®
    [params.header.title]
      # LOGO çš„ URL
      logo = "/img/self.gif"
      # æ ‡é¢˜åç§°
      name = "ricky's blogs"
      # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
      pre = ""
      # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
      post = ""
      # LoveIt æ–°å¢ | 0.2.5 æ˜¯å¦ä¸ºæ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
      typeit = false

  # ä¸»é¡µé…ç½®
  [params.home]
    # LoveIt æ–°å¢ | 0.2.0 RSS æ–‡ç« æ•°ç›®
    rss = 10
    # ä¸»é¡µä¸ªäººä¿¡æ¯
    [params.home.profile]
      enable = true
      # Gravatar é‚®ç®±ï¼Œç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
      gravatarEmail = ""
      # ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
      avatarURL = "/img/self.gif"
      # LoveIt æ›´æ”¹ | 0.2.7 ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™æ ‡é¢˜ (æ”¯æŒ HTML æ ¼å¼)
      title = "Hi"
      # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜ (å…è®¸ HTML æ ¼å¼)
      subtitle = "^.^"
      # æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
      typeit = false
      # æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤è´¦å·
      social = true
      # LoveIt æ–°å¢ | 0.2.0 å…è´£å£°æ˜ (æ”¯æŒ HTML æ ¼å¼)
      disclaimer = ""
    # ä¸»é¡µæ–‡ç« åˆ—è¡¨
    [params.home.posts]
      enable = true
      # ä¸»é¡µæ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
      paginate = 5
      # LoveIt åˆ é™¤ | 0.2.0 è¢« params.page ä¸­çš„ hiddenFromHomePage æ›¿ä»£
      # å½“ä½ æ²¡æœ‰åœ¨æ–‡ç« å‰ç½®å‚æ•°ä¸­è®¾ç½® "hiddenFromHomePage" æ—¶çš„é»˜è®¤è¡Œä¸º
      defaultHiddenFromHomePage = false

  # é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
  [params.footer]
    enable = true
    # LoveIt æ–°å¢ | 0.2.0 è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
    custom = ''
    # LoveIt æ–°å¢ | 0.2.0 æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
    hugo = false
    # LoveIt æ–°å¢ | 0.2.0 æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
    copyright = true
    # LoveIt æ–°å¢ | 0.2.0 æ˜¯å¦æ˜¾ç¤ºä½œè€…
    author = true
    # ç½‘ç«™åˆ›ç«‹å¹´ä»½
    since = 2023
    # ICP å¤‡æ¡ˆä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ (æ”¯æŒ HTML æ ¼å¼)
    icp = '<a style="color:#000" href="https://beian.miit.gov.cn/" target="_blank">ç²¤ICPå¤‡2023011986å·-1 | </a>  <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=44030502009810" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;"><img src="/img/beian.png" style="float:left;"/>ç²¤å…¬ç½‘å®‰å¤‡ 44030502009810å·</a>'
    # è®¸å¯åè®®ä¿¡æ¯ (æ”¯æŒ HTML æ ¼å¼)
    #license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  # LoveIt æ–°å¢ | 0.2.0 Section (æ‰€æœ‰æ–‡ç« ) é¡µé¢é…ç½®
  [params.section]
    # section é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
    paginate = 20
    # æ—¥æœŸæ ¼å¼ (æœˆå’Œæ—¥)
    dateFormat = "2006-01-02"
    # RSS æ–‡ç« æ•°ç›®
    rss = 10
    # æ˜¾ç¤ºæœ€è¿‘æ›´æ–°æ–‡ç« çš„æ•°é‡
    lastUpdatedSize = 5

  # LoveIt æ–°å¢ | 0.2.0 List (ç›®å½•æˆ–æ ‡ç­¾) é¡µé¢é…ç½®
  [params.list]
    # list é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
    paginate = 5
    # æ—¥æœŸæ ¼å¼ (æœˆå’Œæ—¥)
    dateFormat = "01-02"
    # RSS æ–‡ç« æ•°ç›®
    rss = 10
    #lastUpdatedSize = 5

  # LoveIt æ–°å¢ | 0.2.0 åº”ç”¨å›¾æ ‡é…ç½®
  [params.app]
    # å½“æ·»åŠ åˆ° iOS ä¸»å±å¹•æˆ–è€… Android å¯åŠ¨å™¨æ—¶çš„æ ‡é¢˜, è¦†ç›–é»˜è®¤æ ‡é¢˜
    title = "ricky_zhf"
    # æ˜¯å¦éšè—ç½‘ç«™å›¾æ ‡èµ„æºé“¾æ¥
    noFavicon = false
    # æ›´ç°ä»£çš„ SVG ç½‘ç«™å›¾æ ‡, å¯æ›¿ä»£æ—§çš„ .png å’Œ .ico æ–‡ä»¶
    svgFavicon = "/img/self.gif"
    # Android æµè§ˆå™¨ä¸»é¢˜è‰²
    themeColor = "#ffffff"
    # Safari å›¾æ ‡é¢œè‰²
    iconColor = "#5bbad5"
    # Windows v8-10ç£è´´é¢œè‰²
    tileColor = "#da532c"

  # LoveIt æ–°å¢ | 0.2.0 æœç´¢é…ç½®
  [params.search]
    enable = true
    # æœç´¢å¼•æ“çš„ç±»å‹ ["lunr", "algolia"]
    type = "lunr"
    # æ–‡ç« å†…å®¹æœ€é•¿ç´¢å¼•é•¿åº¦
    contentLength = 4000
    # æœç´¢æ¡†çš„å ä½æç¤ºè¯­
    placeholder = ""
    # LoveIt æ–°å¢ | 0.2.1 æœ€å¤§ç»“æœæ•°ç›®
    maxResultLength = 10
    # LoveIt æ–°å¢ | 0.2.3 ç»“æœå†…å®¹ç‰‡æ®µé•¿åº¦
    snippetLength = 50
    # LoveIt æ–°å¢ | 0.2.1 æœç´¢ç»“æœä¸­é«˜äº®éƒ¨åˆ†çš„ HTML æ ‡ç­¾
    highlightTag = "em"
    # LoveIt æ–°å¢ | 0.2.4 æ˜¯å¦åœ¨æœç´¢ç´¢å¼•ä¸­ä½¿ç”¨åŸºäº baseURL çš„ç»å¯¹è·¯å¾„
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  # ä½œè€…çš„ç¤¾äº¤ä¿¡æ¯è®¾ç½®
  [params.social]
    GitHub = "https://github.com/ricky-zhf"
    #Linkedin = ""
    #Twitter = "xxxx"
    #Instagram = "xxxx"
    #Facebook = "xxxx"
    #Telegram = "xxxx"  
    Email = "568058082@qq.com"
    wechat = "/img/wechat.jpeg"
    RSS = true # LoveIt æ–°å¢ | 0.2.0

  # LoveIt æ›´æ”¹ | 0.2.0 æ–‡ç« é¡µé¢å…¨å±€é…ç½®
  [params.page]
    # LoveIt æ–°å¢ | 0.2.0 æ˜¯å¦åœ¨ä¸»é¡µéšè—ä¸€ç¯‡æ–‡ç« 
    hiddenFromHomePage = false
    # LoveIt æ–°å¢ | 0.2.0 æ˜¯å¦åœ¨æœç´¢ç»“æœä¸­éšè—ä¸€ç¯‡æ–‡ç« 
    hiddenFromSearch = false
    # LoveIt æ–°å¢ | 0.2.0 æ˜¯å¦ä½¿ç”¨ twemoji
    twemoji = false
    # æ˜¯å¦ä½¿ç”¨ lightgallery
    lightgallery = false
    # LoveIt æ–°å¢ | 0.2.0 æ˜¯å¦ä½¿ç”¨ ruby æ‰©å±•è¯­æ³•
    ruby = true
    # LoveIt æ–°å¢ | 0.2.0 æ˜¯å¦ä½¿ç”¨ fraction æ‰©å±•è¯­æ³•
    fraction = true
    # LoveIt æ–°å¢ | 0.2.0 æ˜¯å¦ä½¿ç”¨ fontawesome æ‰©å±•è¯­æ³•
    fontawesome = true
    # æ˜¯å¦åœ¨æ–‡ç« é¡µé¢æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£é“¾æ¥
    linkToMarkdown = true
    # LoveIt æ–°å¢ | 0.2.4 æ˜¯å¦åœ¨ RSS ä¸­æ˜¾ç¤ºå…¨æ–‡å†…å®¹
    rssFullText = false
    # LoveIt æ–°å¢ | 0.2.0 ç›®å½•é…ç½®
    [params.page.toc]
      # æ˜¯å¦ä½¿ç”¨ç›®å½•
      enable = true
      # LoveIt æ–°å¢ | 0.2.9 æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
      keepStatic = false
      # æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
      auto = false
    # LoveIt æ–°å¢ | 0.2.0 ä»£ç é…ç½®
    [params.page.code]
      # æ˜¯å¦æ˜¾ç¤ºä»£ç å—çš„å¤åˆ¶æŒ‰é’®
      copy = true
      # é»˜è®¤å±•å¼€æ˜¾ç¤ºçš„ä»£ç è¡Œæ•°
      maxShownLines = 50
    # LoveIt æ›´æ”¹ | 0.2.0 KaTeX æ•°å­¦å…¬å¼
    [params.page.math]
      enable = true
      # LoveIt æ›´æ”¹ | 0.2.11 é»˜è®¤è¡Œå†…å®šç•Œç¬¦æ˜¯ $ ... $ å’Œ \( ... \)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # LoveIt æ›´æ”¹ | 0.2.11 é»˜è®¤å—å®šç•Œç¬¦æ˜¯ $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} å’Œä¸€äº›å…¶å®ƒçš„å‡½æ•°
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # KaTeX æ’ä»¶ copy_tex
      copyTex = true
      # KaTeX æ’ä»¶ mhchem
      mhchem = true
    # LoveIt æ–°å¢ | 0.2.0 Mapbox GL JS é…ç½®
    [params.page.mapbox]
      # Mapbox GL JS çš„ access token
      accessToken = ""
      # æµ…è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      # æ·±è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      # æ˜¯å¦æ·»åŠ  NavigationControl
      navigation = true
      # æ˜¯å¦æ·»åŠ  GeolocateControl
      geolocate = true
      # æ˜¯å¦æ·»åŠ  ScaleControl
      scale = true
      # æ˜¯å¦æ·»åŠ  FullscreenControl
      fullscreen = true
    # LoveIt æ›´æ”¹ | 0.2.0 æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false

      Weibo = false
      Blogger = false
      Baidu = false

    # LoveIt æ›´æ”¹ | 0.2.0 è¯„è®ºç³»ç»Ÿè®¾ç½®
    [params.page.comment]
      enable = true
      # Disqus è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.disqus]
        # LoveIt æ–°å¢ | 0.1.1
        enable = false
        # Disqus çš„ shortnameï¼Œç”¨æ¥åœ¨æ–‡ç« ä¸­å¯ç”¨ Disqus è¯„è®ºç³»ç»Ÿ
        shortname = ""
      # Gitalk è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.gitalk]
        # LoveIt æ–°å¢ | 0.1.1
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      # Valine è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        # ä¸ºç©ºæ—¶è‡ªåŠ¨é€‚é…å½“å‰ä¸»é¢˜ i18n é…ç½®
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        # LoveIt æ–°å¢ | 0.2.6 emoji æ•°æ®æ–‡ä»¶åç§°, é»˜è®¤æ˜¯ "google.yml"
        # ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
        # ä½äº "themes/LoveIt/assets/lib/valine/emoji/" ç›®å½•
        # å¯ä»¥åœ¨ä½ çš„é¡¹ç›®ä¸‹ç›¸åŒè·¯å¾„å­˜æ”¾ä½ è‡ªå·±çš„æ•°æ®æ–‡ä»¶:
        # "assets/lib/valine/emoji/"
        emoji = ""
      # Facebook è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        # ä¸ºç©ºæ—¶è‡ªåŠ¨é€‚é…å½“å‰ä¸»é¢˜ i18n é…ç½®
        languageCode = "zh_CN"
      # LoveIt æ–°å¢ | 0.2.0 Telegram Comments è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      # LoveIt æ–°å¢ | 0.2.0 Commento è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.commento]
        enable = false
      # LoveIt æ–°å¢ | 0.2.5 utterances è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.utterances]
        enable = false
        # owner/repo
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
      # giscus comment è¯„è®ºç³»ç»Ÿè®¾ç½® (https://giscus.app/zh-CN)
      [params.page.comment.giscus]
        # ä½ å¯ä»¥å‚è€ƒå®˜æ–¹æ–‡æ¡£æ¥ä½¿ç”¨ä¸‹åˆ—é…ç½®
        enable = false
        repo = ""
        repoId = ""
        category = "Announcements"
        categoryId = ""
        # ä¸ºç©ºæ—¶è‡ªåŠ¨é€‚é…å½“å‰ä¸»é¢˜ i18n é…ç½®
        lang = ""
        mapping = "pathname"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom"
        lazyLoading = false
        lightTheme = "light"
        darkTheme = "dark"
    # LoveIt æ–°å¢ | 0.2.7 ç¬¬ä¸‰æ–¹åº“é…ç½®
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # ä½äº "assets/"
        # æˆ–è€…
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # ä½äº "assets/"
        # æˆ–è€…
        # someJavascript = "https://cdn.example.com/some.js"
    # LoveIt æ›´æ”¹ | 0.2.10 é¡µé¢ SEO é…ç½®
    [params.page.seo]
      # å›¾ç‰‡ URL
      images = []
      # å‡ºç‰ˆè€…ä¿¡æ¯
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""

  # LoveIt æ–°å¢ | 0.2.5 TypeIt é…ç½®
  [params.typeit]
    # æ¯ä¸€æ­¥çš„æ‰“å­—é€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
    speed = 100
    # å…‰æ ‡çš„é—ªçƒé€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
    cursorSpeed = 1000
    # å…‰æ ‡çš„å­—ç¬¦ (æ”¯æŒ HTML æ ¼å¼)
    cursorChar = "|"
    # æ‰“å­—ç»“æŸä¹‹åå…‰æ ‡çš„æŒç»­æ—¶é—´ (å•ä½æ˜¯æ¯«ç§’, "-1" ä»£è¡¨æ— é™å¤§)
    duration = -1

  # ç½‘ç«™éªŒè¯ä»£ç ï¼Œç”¨äº Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  # LoveIt æ–°å¢ | 0.2.10 ç½‘ç«™ SEO é…ç½®
  [params.seo]
    # å›¾ç‰‡ URL
    image = ""
    # ç¼©ç•¥å›¾ URL
    thumbnailUrl = ""

  # LoveIt æ–°å¢ | 0.2.0 ç½‘ç«™åˆ†æé…ç½®
  # Analytics config
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = ""
      # whether to anonymize IP
      # æ˜¯å¦åŒ¿ååŒ–ç”¨æˆ· IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # server url for your tracker if you're self hosting
      # è‡ªè¡Œæ‰˜ç®¡è¿½è¸ªå™¨æ—¶çš„ä¸»æœºè·¯å¾„
      server = ""
    # ç™¾åº¦ç»Ÿè®¡
    [params.analytics.baidu]
      id = "7bc6bd2807bc80753aa301722537a86e"


# lastmodè‡ªåŠ¨æ›´æ–°æ—¶é—´
# [frontmatter]
#   lastmod = [":fileModTime", "lastmod"]

[autonumber]
  autonumber = true

# ç½‘ç«™åœ°å›¾é…ç½®
[sitemap]
  #changefreq = "weekly"
  filename = "sitemap.xml"
  #priority = 0.5